// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RegisterUser', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('RegisterUser', async function() {
    await driver.get("https://www.technopolis.bg/bg/")
    await driver.manage().window().setRect({ width: 1536, height: 864 })
    await driver.findElement(By.css(".item-profile")).click()
    await driver.findElement(By.css(".bottom:nth-child(10) .button")).click()
    await driver.findElement(By.id("titleKey")).click()
    {
      const dropdown = await driver.findElement(By.id("titleKey"))
      await dropdown.findElement(By.xpath("//option[. = 'Г-н']")).click()
    }
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("Joro")
    await driver.findElement(By.id("lastName")).sendKeys("Ivanov")
    vars["email"] = await driver.executeScript("return \'hello\' + Math.floor(Math.random() * 100000) + \'@test.com\';")
    await driver.findElement(By.id("email")).sendKeys(vars["email"])
    await driver.findElement(By.id("phone")).sendKeys("0876123456")
    await driver.findElement(By.id("nolog_password")).click()
    vars["password"] = await driver.executeScript("return Math.random().toString(36).substring(2,8);")
    await driver.findElement(By.id("nolog_password")).sendKeys(vars["password"])
    await driver.findElement(By.id("nolog_passwordVerify")).click()
    await driver.findElement(By.id("nolog_passwordVerify")).sendKeys(vars["password"])
    await driver.findElement(By.css(".checkbox:nth-child(2) > .checkbox-item")).click()
    await driver.findElement(By.css(".g-recaptcha")).click()
    await driver.findElement(By.id("logoutId")).click()
    await driver.close()
  })
})
